name: report action
on:
    schedule:
      - cron:  '*/5 * * * *'

jobs:
    getInfo:
        name: Get info from Sunset and sunrise times
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: install dep
              run: pip install -r requirements.txt

            - name: Export variables
              run: | 
                export LAT=${{ secrets.LATITUD }}
                export LON=${{ secrets.LONGITUD }}

            - name: Get Result
              run:
                python get_results.py --lat $LAT --lon $LON