name: report action
on:
    schedule:
      - cron:  '*/5 * * * *'


jobs:
    getInfo:
        name: Get info from Sunset and sunrise times
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: install dep
              run: pip install -r requirements.txt

            - name: Get Result
              run:
                python get_results.py --lat ${{ secrets.LAT }} --lon ${{ secrets.LON }}

            - name: Check Git changes
              run: |
                export time=$(date +%F)
                git config --global user.email "nahuelq.78@gmail.com"
                git config --global user.name "matiasz8"
                git status 
                git add . 
                git commit -m "update $time"
                git push