name: report action
# on:
#     schedule:
#       - cron:  '*/5 * * * *'
on: [push]


jobs:
    getInfo:
        name: Get info from Sunset and sunrise times
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: install dep
              run: pip install -r requirements.txt

            - run: ls
            
            - name: Get Result
              run:
                python get_results.py --lat ${{ secrets.LAT }} --lon ${{ secrets.LON }}